name       : glew110
version    : 1.10.0
release    : 8
source     :
    - http://jaist.dl.sourceforge.net/project/glew/glew/1.10.0/glew-1.10.0.tgz : 99c41320b63f6860869b5fb9af9a1854b15582796c64ee3dfd7096dc0c89f307
license    :
    - GPL-2.0
    - MIT
    - BSD-3-Clause
summary    : Binary Compatibility Library
component  : binary.compat
description: |
    Binary Compatibility Library - it is forbidden to build against this library
builddeps  :
    - pkgconfig(xmu)
    - pkgconfig32(xmu)
    - pkgconfig(xi)
    - pkgconfig32(xi)
    - pkgconfig(glu)
    - pkgconfig32(glu)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
setup      : |
    %patch -p1 < $pkgfiles/0001-Underp-buildsystem.patch
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        libdir="lib32"
        ARCH64="false"
    else
        libdir="lib64"
        ARCH64="true"
    fi
    %make CC="${CC}" LD="${CC}" ALIBDIR="${libdir}" ARCH64="${ARCH64}"
install    : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        libdir="lib32"
        ARCH64="false"
    else
        libdir="lib64"
        ARCH64="true"
    fi
    %make_install CC="${CC}" LD="${CC}" ALIBDIR="${libdir}" ARCH64="${ARCH64}" GLEW_DEST="$installdir/usr"
    rm -vf "$installdir"/%libdir%/*.a
    rm -vf "$installdir"/%libdir%/*.so
    rm -rvf "$installdir"/%libdir%/pkgconfig
    rm -rvf "$installdir"/usr/include
